version: '3.7'

services:
  react:
    container_name: as-front
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: adminsmart_frontend
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    ports:
      - 3000:3000
    # command: npm start